name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: ["3.0.0", "stable"]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
          
      - name: Show Dart version
        run: dart --version
        
      - name: Install dependencies
        run: dart pub get
        
      - name: Run tests with detailed output
        run: dart test --reporter expanded
        continue-on-error: true
        
      - name: Run formatter
        run: dart format --output=none --set-exit-if-changed .
        
      - name: Run analyzer
        run: dart analyze --fatal-infos
        
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.sdk }}
          path: test/**/output.txt
